# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/config/cluster_config.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from secretflow_serving_lib.secretflow_serving.config import tls_config_pb2 as secretflow__serving_dot_config_dot_tls__config__pb2
from secretflow_serving_lib.secretflow_serving.config import retry_policy_config_pb2 as secretflow__serving_dot_config_dot_retry__policy__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.secretflow_serving/config/cluster_config.proto\x12\x12secretflow.serving\x1a*secretflow_serving/config/tls_config.proto\x1a\x33secretflow_serving/config/retry_policy_config.proto\"\x90\x02\n\x0b\x43hannelDesc\x12\x10\n\x08protocol\x18\x01 \x01(\t\x12\x16\n\x0erpc_timeout_ms\x18\x02 \x01(\x05\x12\x1a\n\x12\x63onnect_timeout_ms\x18\x03 \x01(\x05\x12\x31\n\ntls_config\x18\x04 \x01(\x0b\x32\x1d.secretflow.serving.TlsConfig\x12\x1f\n\x17handshake_max_retry_cnt\x18\x05 \x01(\x05\x12#\n\x1bhandshake_retry_interval_ms\x18\x06 \x01(\x05\x12\x42\n\x13retry_policy_config\x18\x07 \x01(\x0b\x32%.secretflow.serving.RetryPolicyConfig\"(\n\tPartyDesc\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\x87\x01\n\rClusterConfig\x12.\n\x07parties\x18\x01 \x03(\x0b\x32\x1d.secretflow.serving.PartyDesc\x12\x0f\n\x07self_id\x18\x02 \x01(\t\x12\x35\n\x0c\x63hannel_desc\x18\x03 \x01(\x0b\x32\x1f.secretflow.serving.ChannelDescb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.config.cluster_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHANNELDESC']._serialized_start=168
  _globals['_CHANNELDESC']._serialized_end=440
  _globals['_PARTYDESC']._serialized_start=442
  _globals['_PARTYDESC']._serialized_end=482
  _globals['_CLUSTERCONFIG']._serialized_start=485
  _globals['_CLUSTERCONFIG']._serialized_end=620
# @@protoc_insertion_point(module_scope)
