# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/config/feature_config.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from secretflow_serving_lib.secretflow_serving.config import tls_config_pb2 as secretflow__serving_dot_config_dot_tls__config__pb2
from secretflow_serving_lib.secretflow_serving.config import retry_policy_config_pb2 as secretflow__serving_dot_config_dot_retry__policy__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.secretflow_serving/config/feature_config.proto\x12\x12secretflow.serving\x1a*secretflow_serving/config/tls_config.proto\x1a\x33secretflow_serving/config/retry_policy_config.proto\"\x80\x02\n\x13\x46\x65\x61tureSourceConfig\x12\x34\n\tmock_opts\x18\x01 \x01(\x0b\x32\x1f.secretflow.serving.MockOptionsH\x00\x12\x34\n\thttp_opts\x18\x02 \x01(\x0b\x32\x1f.secretflow.serving.HttpOptionsH\x00\x12\x32\n\x08\x63sv_opts\x18\x03 \x01(\x0b\x32\x1e.secretflow.serving.CsvOptionsH\x00\x12>\n\x0estreaming_opts\x18\x04 \x01(\x0b\x32$.secretflow.serving.StreamingOptionsH\x00\x42\t\n\x07options\"=\n\x0bMockOptions\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .secretflow.serving.MockDataType\"\xd9\x01\n\x0bHttpOptions\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x11\n\tenable_lb\x18\x02 \x01(\x08\x12\x1a\n\x12\x63onnect_timeout_ms\x18\x03 \x01(\x05\x12\x12\n\ntimeout_ms\x18\x04 \x01(\x05\x12\x31\n\ntls_config\x18\x05 \x01(\x0b\x32\x1d.secretflow.serving.TlsConfig\x12\x42\n\x13retry_policy_config\x18\x06 \x01(\x0b\x32%.secretflow.serving.RetryPolicyConfig\"\\\n\nCsvOptions\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x0f\n\x07id_name\x18\x02 \x01(\t\x12\x16\n\x0estreaming_mode\x18\x0b \x01(\x08\x12\x12\n\nblock_size\x18\x0c \x01(\x05\"_\n\x10StreamingOptions\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x13\n\x0b\x66ile_format\x18\x02 \x01(\t\x12\x0f\n\x07id_name\x18\x03 \x01(\t\x12\x12\n\nblock_size\x18\x0c \x01(\x05*I\n\x0cMockDataType\x12\x1a\n\x16INVALID_MOCK_DATA_TYPE\x10\x00\x12\x0e\n\nMDT_RANDOM\x10\x01\x12\r\n\tMDT_FIXED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.config.feature_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MOCKDATATYPE']._serialized_start=900
  _globals['_MOCKDATATYPE']._serialized_end=973
  _globals['_FEATURESOURCECONFIG']._serialized_start=168
  _globals['_FEATURESOURCECONFIG']._serialized_end=424
  _globals['_MOCKOPTIONS']._serialized_start=426
  _globals['_MOCKOPTIONS']._serialized_end=487
  _globals['_HTTPOPTIONS']._serialized_start=490
  _globals['_HTTPOPTIONS']._serialized_end=707
  _globals['_CSVOPTIONS']._serialized_start=709
  _globals['_CSVOPTIONS']._serialized_end=801
  _globals['_STREAMINGOPTIONS']._serialized_start=803
  _globals['_STREAMINGOPTIONS']._serialized_end=898
# @@protoc_insertion_point(module_scope)
