# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/config/logging_config.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.secretflow_serving/config/logging_config.proto\x12\x12secretflow.serving\"\x90\x01\n\rLoggingConfig\x12\x17\n\x0fsystem_log_path\x18\x01 \x01(\t\x12/\n\tlog_level\x18\x02 \x01(\x0e\x32\x1c.secretflow.serving.LogLevel\x12\x19\n\x11max_log_file_size\x18\x03 \x01(\x05\x12\x1a\n\x12max_log_file_count\x18\x04 \x01(\x05*s\n\x08LogLevel\x12\x15\n\x11INVALID_LOG_LEVEL\x10\x00\x12\x13\n\x0f\x44\x45\x42UG_LOG_LEVEL\x10\x01\x12\x12\n\x0eINFO_LOG_LEVEL\x10\x02\x12\x12\n\x0eWARN_LOG_LEVEL\x10\x03\x12\x13\n\x0f\x45RROR_LOG_LEVEL\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.config.logging_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGLEVEL']._serialized_start=217
  _globals['_LOGLEVEL']._serialized_end=332
  _globals['_LOGGINGCONFIG']._serialized_start=71
  _globals['_LOGGINGCONFIG']._serialized_end=215
# @@protoc_insertion_point(module_scope)
