# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/config/model_config.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from secretflow_serving_lib.secretflow_serving.config import tls_config_pb2 as secretflow__serving_dot_config_dot_tls__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,secretflow_serving/config/model_config.proto\x12\x12secretflow.serving\x1a*secretflow_serving/config/tls_config.proto\"\x10\n\x0e\x46ileSourceMeta\"s\n\x0eHttpSourceMeta\x12\x1a\n\x12\x63onnect_timeout_ms\x18\x01 \x01(\x05\x12\x12\n\ntimeout_ms\x18\x02 \x01(\x05\x12\x31\n\ntls_config\x18\x03 \x01(\x0b\x32\x1d.secretflow.serving.TlsConfig\"R\n\x0c\x44PSourceMeta\x12\x0f\n\x07\x64m_host\x18\x01 \x01(\t\x12\x31\n\ntls_config\x18\x02 \x01(\x0b\x32\x1d.secretflow.serving.TlsConfig\"q\n\rOSSSourceMeta\x12\x12\n\naccess_key\x18\x01 \x01(\t\x12\x12\n\nsecret_key\x18\x02 \x01(\t\x12\x16\n\x0evirtual_hosted\x18\x03 \x01(\x08\x12\x10\n\x08\x65ndpoint\x18\x04 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x05 \x01(\t\"\x95\x03\n\x0bModelConfig\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x11\n\tbase_path\x18\x02 \x01(\t\x12\x13\n\x0bsource_path\x18\x03 \x01(\t\x12\x15\n\rsource_sha256\x18\x04 \x01(\t\x12\x33\n\x0bsource_type\x18\x05 \x01(\x0e\x32\x1e.secretflow.serving.SourceType\x12>\n\x10\x66ile_source_meta\x18\x06 \x01(\x0b\x32\".secretflow.serving.FileSourceMetaH\x00\x12<\n\x0foss_source_meta\x18\x07 \x01(\x0b\x32!.secretflow.serving.OSSSourceMetaH\x00\x12>\n\x10http_source_meta\x18\x08 \x01(\x0b\x32\".secretflow.serving.HttpSourceMetaH\x00\x12:\n\x0e\x64p_source_meta\x18\t \x01(\x0b\x32 .secretflow.serving.DPSourceMetaH\x00\x42\x06\n\x04kind*V\n\nSourceType\x12\x17\n\x13INVALID_SOURCE_TYPE\x10\x00\x12\x0b\n\x07ST_FILE\x10\x01\x12\n\n\x06ST_OSS\x10\x02\x12\x0b\n\x07ST_HTTP\x10\x03\x12\t\n\x05ST_DP\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.config.model_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SOURCETYPE']._serialized_start=854
  _globals['_SOURCETYPE']._serialized_end=940
  _globals['_FILESOURCEMETA']._serialized_start=112
  _globals['_FILESOURCEMETA']._serialized_end=128
  _globals['_HTTPSOURCEMETA']._serialized_start=130
  _globals['_HTTPSOURCEMETA']._serialized_end=245
  _globals['_DPSOURCEMETA']._serialized_start=247
  _globals['_DPSOURCEMETA']._serialized_end=329
  _globals['_OSSSOURCEMETA']._serialized_start=331
  _globals['_OSSSOURCEMETA']._serialized_end=444
  _globals['_MODELCONFIG']._serialized_start=447
  _globals['_MODELCONFIG']._serialized_end=852
# @@protoc_insertion_point(module_scope)
