# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/config/retry_policy_config.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3secretflow_serving/config/retry_policy_config.proto\x12\x12secretflow.serving\")\n\x12\x46ixedBackOffConfig\x12\x13\n\x0binterval_ms\x18\x01 \x01(\x05\";\n\x18\x45xponentialBackOffConfig\x12\x0f\n\x07init_ms\x18\x01 \x01(\x05\x12\x0e\n\x06\x66\x61\x63tor\x18\x02 \x01(\x05\"5\n\x13RandomBackOffConfig\x12\x0e\n\x06min_ms\x18\x01 \x01(\x05\x12\x0e\n\x06max_ms\x18\x02 \x01(\x05\"\x96\x03\n\x11RetryPolicyConfig\x12\x14\n\x0cretry_custom\x18\x01 \x01(\x08\x12\x18\n\x10retry_aggressive\x18\x02 \x01(\x08\x12\x17\n\x0fmax_retry_count\x18\x03 \x01(\x05\x12@\n\x0c\x62\x61\x63koff_mode\x18\x04 \x01(\x0e\x32*.secretflow.serving.RetryPolicyBackOffMode\x12\x46\n\x14\x66ixed_backoff_config\x18\x05 \x01(\x0b\x32&.secretflow.serving.FixedBackOffConfigH\x00\x12R\n\x1a\x65xponential_backoff_config\x18\x06 \x01(\x0b\x32,.secretflow.serving.ExponentialBackOffConfigH\x00\x12H\n\x15random_backoff_config\x18\x07 \x01(\x0b\x32\'.secretflow.serving.RandomBackOffConfigH\x00\x42\x10\n\x0e\x62\x61\x63koff_config*j\n\x16RetryPolicyBackOffMode\x12\x10\n\x0cINVALID_MODE\x10\x00\x12\x11\n\rFIXED_BACKOFF\x10\x01\x12\x17\n\x13\x45XPONENTIAL_BACKOFF\x10\x02\x12\x12\n\x0eRANDOM_BACKOFF\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.config.retry_policy_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RETRYPOLICYBACKOFFMODE']._serialized_start=643
  _globals['_RETRYPOLICYBACKOFFMODE']._serialized_end=749
  _globals['_FIXEDBACKOFFCONFIG']._serialized_start=75
  _globals['_FIXEDBACKOFFCONFIG']._serialized_end=116
  _globals['_EXPONENTIALBACKOFFCONFIG']._serialized_start=118
  _globals['_EXPONENTIALBACKOFFCONFIG']._serialized_end=177
  _globals['_RANDOMBACKOFFCONFIG']._serialized_start=179
  _globals['_RANDOMBACKOFFCONFIG']._serialized_end=232
  _globals['_RETRYPOLICYCONFIG']._serialized_start=235
  _globals['_RETRYPOLICYCONFIG']._serialized_end=641
# @@protoc_insertion_point(module_scope)
