# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/config/serving_config.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from secretflow_serving_lib.secretflow_serving.config import server_config_pb2 as secretflow__serving_dot_config_dot_server__config__pb2
from secretflow_serving_lib.secretflow_serving.config import cluster_config_pb2 as secretflow__serving_dot_config_dot_cluster__config__pb2
from secretflow_serving_lib.secretflow_serving.config import model_config_pb2 as secretflow__serving_dot_config_dot_model__config__pb2
from secretflow_serving_lib.secretflow_serving.config import feature_config_pb2 as secretflow__serving_dot_config_dot_feature__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.secretflow_serving/config/serving_config.proto\x12\x12secretflow.serving\x1a-secretflow_serving/config/server_config.proto\x1a.secretflow_serving/config/cluster_config.proto\x1a,secretflow_serving/config/model_config.proto\x1a.secretflow_serving/config/feature_config.proto\"\x86\x02\n\rServingConfig\x12\n\n\x02id\x18\x01 \x01(\t\x12\x35\n\x0bserver_conf\x18\x02 \x01(\x0b\x32 .secretflow.serving.ServerConfig\x12\x33\n\nmodel_conf\x18\x03 \x01(\x0b\x32\x1f.secretflow.serving.ModelConfig\x12\x37\n\x0c\x63luster_conf\x18\x04 \x01(\x0b\x32!.secretflow.serving.ClusterConfig\x12\x44\n\x13\x66\x65\x61ture_source_conf\x18\x05 \x01(\x0b\x32\'.secretflow.serving.FeatureSourceConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.config.serving_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVINGCONFIG']._serialized_start=260
  _globals['_SERVINGCONFIG']._serialized_end=522
# @@protoc_insertion_point(module_scope)
