# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/config/server_config.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from secretflow_serving_lib.secretflow_serving.config import tls_config_pb2 as secretflow__serving_dot_config_dot_tls__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-secretflow_serving/config/server_config.proto\x12\x12secretflow.serving\x1a*secretflow_serving/config/tls_config.proto\"\x91\x03\n\x0cServerConfig\x12M\n\x0f\x66\x65\x61ture_mapping\x18\x01 \x03(\x0b\x32\x34.secretflow.serving.ServerConfig.FeatureMappingEntry\x12\x31\n\ntls_config\x18\x02 \x01(\x0b\x32\x1d.secretflow.serving.TlsConfig\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x14\n\x0cservice_port\x18\x04 \x01(\x05\x12\x1a\n\x12\x63ommunication_port\x18\x05 \x01(\x05\x12!\n\x19\x62rpc_builtin_service_port\x18\x0b \x01(\x05\x12\x1c\n\x14metrics_exposer_port\x18\x0c \x01(\x05\x12\x12\n\nworker_num\x18\r \x01(\x05\x12\x17\n\x0fmax_concurrency\x18\x0e \x01(\x05\x12\x1a\n\x12op_exec_worker_num\x18\x0f \x01(\x05\x1a\x35\n\x13\x46\x65\x61tureMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.config.server_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVERCONFIG_FEATUREMAPPINGENTRY']._options = None
  _globals['_SERVERCONFIG_FEATUREMAPPINGENTRY']._serialized_options = b'8\001'
  _globals['_SERVERCONFIG']._serialized_start=114
  _globals['_SERVERCONFIG']._serialized_end=515
  _globals['_SERVERCONFIG_FEATUREMAPPINGENTRY']._serialized_start=462
  _globals['_SERVERCONFIG_FEATUREMAPPINGENTRY']._serialized_end=515
# @@protoc_insertion_point(module_scope)
