# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/config/tls_config.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*secretflow_serving/config/tls_config.proto\x12\x12secretflow.serving\"U\n\tTlsConfig\x12\x18\n\x10\x63\x65rtificate_path\x18\x01 \x01(\t\x12\x18\n\x10private_key_path\x18\x02 \x01(\t\x12\x14\n\x0c\x63\x61_file_path\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.config.tls_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TLSCONFIG']._serialized_start=66
  _globals['_TLSCONFIG']._serialized_end=151
# @@protoc_insertion_point(module_scope)
