# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/config/trace_config.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,secretflow_serving/config/trace_config.proto\x12\x12secretflow.serving\"k\n\x0eTraceLogConfig\x12\x16\n\x0etrace_log_path\x18\x01 \x01(\t\x12\x1f\n\x17max_trace_log_file_size\x18\x02 \x01(\x05\x12 \n\x18max_trace_log_file_count\x18\x03 \x01(\x05\"c\n\x0bTraceConfig\x12\x18\n\x10trace_log_enable\x18\x01 \x01(\x08\x12:\n\x0etrace_log_conf\x18\x02 \x01(\x0b\x32\".secretflow.serving.TraceLogConfigb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.config.trace_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRACELOGCONFIG']._serialized_start=68
  _globals['_TRACELOGCONFIG']._serialized_end=175
  _globals['_TRACECONFIG']._serialized_start=177
  _globals['_TRACECONFIG']._serialized_end=276
# @@protoc_insertion_point(module_scope)
