# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/config/trace_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,secretflow_serving/config/trace_config.proto\x12\x12secretflow.serving\"\xa4\x01\n\x0eTraceLogConfig\x12$\n\x0etrace_log_path\x18\x01 \x01(\tR\x0ctraceLogPath\x12\x34\n\x17max_trace_log_file_size\x18\x02 \x01(\x05R\x13maxTraceLogFileSize\x12\x36\n\x18max_trace_log_file_count\x18\x03 \x01(\x05R\x14maxTraceLogFileCount\"\x81\x01\n\x0bTraceConfig\x12(\n\x10trace_log_enable\x18\x01 \x01(\x08R\x0etraceLogEnable\x12H\n\x0etrace_log_conf\x18\x02 \x01(\x0b\x32\".secretflow.serving.TraceLogConfigR\x0ctraceLogConfb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.config.trace_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRACELOGCONFIG._serialized_start=69
  _TRACELOGCONFIG._serialized_end=233
  _TRACECONFIG._serialized_start=236
  _TRACECONFIG._serialized_end=365
# @@protoc_insertion_point(module_scope)
