# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/protos/compute_trace.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-secretflow_serving/protos/compute_trace.proto\x12\x1asecretflow.serving.compute\"\xbf\x01\n\x06Scalar\x12\x0c\n\x02i8\x18\x01 \x01(\x05H\x00\x12\r\n\x03ui8\x18\x02 \x01(\x05H\x00\x12\r\n\x03i16\x18\x03 \x01(\x05H\x00\x12\x0e\n\x04ui16\x18\x04 \x01(\x05H\x00\x12\r\n\x03i32\x18\x05 \x01(\x05H\x00\x12\x0e\n\x04ui32\x18\x06 \x01(\rH\x00\x12\r\n\x03i64\x18\x07 \x01(\x03H\x00\x12\x0e\n\x04ui64\x18\x08 \x01(\x04H\x00\x12\x0b\n\x01\x66\x18\t \x01(\x02H\x00\x12\x0b\n\x01\x64\x18\n \x01(\x01H\x00\x12\x0b\n\x01s\x18\x0b \x01(\tH\x00\x12\x0b\n\x01\x62\x18\x0c \x01(\x08H\x00\x42\x07\n\x05value\"h\n\rFunctionInput\x12\x11\n\x07\x64\x61ta_id\x18\x01 \x01(\x05H\x00\x12;\n\rcustom_scalar\x18\x02 \x01(\x0b\x32\".secretflow.serving.compute.ScalarH\x00\x42\x07\n\x05value\"!\n\x0e\x46unctionOutput\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x01(\x05\"\xaa\x01\n\rFunctionTrace\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0coption_bytes\x18\x02 \x01(\x0c\x12\x39\n\x06inputs\x18\x03 \x03(\x0b\x32).secretflow.serving.compute.FunctionInput\x12:\n\x06output\x18\x04 \x01(\x0b\x32*.secretflow.serving.compute.FunctionOutput\"\\\n\x0c\x43omputeTrace\x12\x0c\n\x04name\x18\x01 \x01(\t\x12>\n\x0b\x66unc_traces\x18\x02 \x03(\x0b\x32).secretflow.serving.compute.FunctionTrace*\x8c\x01\n\x12\x45xtendFunctionName\x12\x1b\n\x17UNKOWN_EX_FUNCTION_NAME\x10\x00\x12\x11\n\rEFN_TB_COLUMN\x10\x01\x12\x15\n\x11\x45\x46N_TB_ADD_COLUMN\x10\x02\x12\x18\n\x14\x45\x46N_TB_REMOVE_COLUMN\x10\x03\x12\x15\n\x11\x45\x46N_TB_SET_COLUMN\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.protos.compute_trace_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXTENDFUNCTIONNAME']._serialized_start=680
  _globals['_EXTENDFUNCTIONNAME']._serialized_end=820
  _globals['_SCALAR']._serialized_start=78
  _globals['_SCALAR']._serialized_end=269
  _globals['_FUNCTIONINPUT']._serialized_start=271
  _globals['_FUNCTIONINPUT']._serialized_end=375
  _globals['_FUNCTIONOUTPUT']._serialized_start=377
  _globals['_FUNCTIONOUTPUT']._serialized_end=410
  _globals['_FUNCTIONTRACE']._serialized_start=413
  _globals['_FUNCTIONTRACE']._serialized_end=583
  _globals['_COMPUTETRACE']._serialized_start=585
  _globals['_COMPUTETRACE']._serialized_end=677
# @@protoc_insertion_point(module_scope)
