# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/protos/data_type.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)secretflow_serving/protos/data_type.proto\x12\x12secretflow.serving*\xd9\x01\n\x08\x44\x61taType\x12\x13\n\x0fUNKNOWN_DT_TYPE\x10\x00\x12\x0b\n\x07\x44T_BOOL\x10\x01\x12\x0c\n\x08\x44T_UINT8\x10\x02\x12\x0b\n\x07\x44T_INT8\x10\x03\x12\r\n\tDT_UINT16\x10\x04\x12\x0c\n\x08\x44T_INT16\x10\x05\x12\r\n\tDT_UINT32\x10\x06\x12\x0c\n\x08\x44T_INT32\x10\x07\x12\r\n\tDT_UINT64\x10\x08\x12\x0c\n\x08\x44T_INT64\x10\t\x12\x0c\n\x08\x44T_FLOAT\x10\x0b\x12\r\n\tDT_DOUBLE\x10\x0c\x12\r\n\tDT_STRING\x10\r\x12\r\n\tDT_BINARY\x10\x0e\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.protos.data_type_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATATYPE']._serialized_start=66
  _globals['_DATATYPE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
