# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/protos/feature.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'secretflow_serving/protos/feature.proto\x12\x12secretflow.serving\"Z\n\x0c\x46\x65\x61tureValue\x12\x0c\n\x04i32s\x18\x01 \x03(\x05\x12\x0c\n\x04i64s\x18\x02 \x03(\x03\x12\n\n\x02\x66s\x18\x03 \x03(\x02\x12\n\n\x02\x64s\x18\x04 \x03(\x01\x12\n\n\x02ss\x18\x05 \x03(\t\x12\n\n\x02\x62s\x18\x06 \x03(\x08\"I\n\x0c\x46\x65\x61tureField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x04type\x18\x02 \x01(\x0e\x32\x1d.secretflow.serving.FieldType\"k\n\x07\x46\x65\x61ture\x12/\n\x05\x66ield\x18\x01 \x01(\x0b\x32 .secretflow.serving.FeatureField\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .secretflow.serving.FeatureValue\":\n\x0c\x46\x65\x61tureParam\x12\x13\n\x0bquery_datas\x18\x01 \x03(\t\x12\x15\n\rquery_context\x18\x02 \x01(\t*\x8a\x01\n\tFieldType\x12\x16\n\x12UNKNOWN_FIELD_TYPE\x10\x00\x12\x0e\n\nFIELD_BOOL\x10\x01\x12\x0f\n\x0b\x46IELD_INT32\x10\x02\x12\x0f\n\x0b\x46IELD_INT64\x10\x03\x12\x0f\n\x0b\x46IELD_FLOAT\x10\x04\x12\x10\n\x0c\x46IELD_DOUBLE\x10\x05\x12\x10\n\x0c\x46IELD_STRING\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.protos.feature_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FIELDTYPE']._serialized_start=400
  _globals['_FIELDTYPE']._serialized_end=538
  _globals['_FEATUREVALUE']._serialized_start=63
  _globals['_FEATUREVALUE']._serialized_end=153
  _globals['_FEATUREFIELD']._serialized_start=155
  _globals['_FEATUREFIELD']._serialized_end=228
  _globals['_FEATURE']._serialized_start=230
  _globals['_FEATURE']._serialized_end=337
  _globals['_FEATUREPARAM']._serialized_start=339
  _globals['_FEATUREPARAM']._serialized_end=397
# @@protoc_insertion_point(module_scope)
