# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secretflow_serving/protos/link_function.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-secretflow_serving/protos/link_function.proto\x12\x12secretflow.serving*\x92\x03\n\x10LinkFunctionType\x12\x13\n\x0fUNKNOWN_LF_TYPE\x10\x00\x12\n\n\x06LF_EXP\x10\x01\x12\x11\n\rLF_RECIPROCAL\x10\x05\x12\x0f\n\x0bLF_IDENTITY\x10\x06\x12\x12\n\x0eLF_SIGMOID_RAW\x10\x0b\x12\x12\n\x0eLF_SIGMOID_MM1\x10\x0c\x12\x12\n\x0eLF_SIGMOID_MM3\x10\r\x12\x11\n\rLF_SIGMOID_GA\x10\x0e\x12\x11\n\rLF_SIGMOID_T1\x10\x0f\x12\x11\n\rLF_SIGMOID_T3\x10\x10\x12\x11\n\rLF_SIGMOID_T5\x10\x11\x12\x11\n\rLF_SIGMOID_T7\x10\x12\x12\x11\n\rLF_SIGMOID_T9\x10\x13\x12\x12\n\x0eLF_SIGMOID_LS7\x10\x14\x12\x13\n\x0fLF_SIGMOID_SEG3\x10\x15\x12\x13\n\x0fLF_SIGMOID_SEG5\x10\x16\x12\x11\n\rLF_SIGMOID_DF\x10\x17\x12\x11\n\rLF_SIGMOID_SR\x10\x18\x12\x14\n\x10LF_SIGMOID_SEGLS\x10\x19\x12\x11\n\rLF_EXP_TAYLOR\x10\x1e\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secretflow_serving.protos.link_function_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LINKFUNCTIONTYPE']._serialized_start=70
  _globals['_LINKFUNCTIONTYPE']._serialized_end=472
# @@protoc_insertion_point(module_scope)
